version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
   
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
  test:
    depends_on:
      - mysqldb
    build: ./
    
    command: ["sh", "./k.sh"]

volumes: 
  db:
