version: '3.8'

services:
 
  app:
    
    build: ./
    restart: unless-stopped
   
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
  test:
    
    build: ./
    command: ["sh", "k.sh"]

volumes: 
  db:
