version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    image: egyhaty/flask:${COMMIT_SHORT_SHA}
    restart: unless-stopped
    ports:
      - "5000:3000"  
    stdin_open: true
    tty: true
    environment:
      - COMMIT_SHORT_SHA=${COMMIT_SHORT_SHA}

volumes: 
  db: