name: ci

on:
  push:
    branches:
      - 'main'
      

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: egyhaty/flask:latest

      - name: Run test cases
        id: run-test-cases
        run: |
          docker pull egyhaty/flask:latest
          docker run -it --name flask  -d flask
          docker exec -it flask bash
          pip install '.[test]'
          pytest
          echo --- Completed test cases ---
              
      
      - name: executing remote ssh commands using Key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          
          script:   |
            docker pull egyhaty/flask:latest
            docker compose up -d --build
            
  