name: First Pipeline
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     #- name: yaml-lint
      # uses: ibiqlik/action-yamllint@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: egyhaty/flask:${{ env.COMMIT_SHORT_SHA }}
          labels: egyhaty/flask:${{ env.COMMIT_SHORT_SHA }}
      - name: Run test cases
        run: |
          docker run -d --name flask egyhaty/flask:${{ env.COMMIT_SHORT_SHA }} ./k.sh
      - name: executing remote ssh commands using Key
        uses: appleboy/ssh-action@v1.0.3
        env:
          tag: ${{ env.COMMIT_SHORT_SHA }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: tag
          script: |
            echo " check $tag "
            echo " export tag=$tag "
            cd /root/flask
            git pull 
            docker-compose up -d 